# Generated by Django 2.2.4 on 2019-11-17 23:58

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('chat', '0003_mensagem_remetente'),
    ]

    operations = [
        migrations.AlterField(
            model_name='mensagem',
            name='cliente',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='cliente', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='mensagem',
            name='restaurante',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='restaurante', to='Delivery.Restaurante'),
        ),
    ]
