# Generated by Django 2.2.4 on 2019-11-17 14:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Delivery', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='usuario',
            name='foto',
            field=models.ImageField(blank=True, null=True, upload_to='Fotos/Usuario'),
        ),
    ]
