# Generated by Django 2.2.4 on 2019-11-16 20:17

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('Delivery', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='pedido_restaurante',
            name='pedido',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='Delivery.Pedido'),
        ),
        migrations.AlterField(
            model_name='pedido_restaurante',
            name='restaurante',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='Delivery.Restaurante'),
        ),
    ]
