# Generated by Django 2.2.4 on 2019-10-27 22:17

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('Delivery', '0002_restaurante_tag_tags'),
    ]

    operations = [
        migrations.AlterField(
            model_name='classificacao_usuario',
            name='usuario',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='restaurante',
            name='slug',
            field=models.SlugField(max_length=1000, unique=True),
        ),
        migrations.AlterField(
            model_name='tags',
            name='nome',
            field=models.CharField(max_length=500, unique=True),
        ),
    ]
