# Generated by Django 2.2.4 on 2019-11-17 17:09

import cloudinary.models
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Delivery', '0002_auto_20191117_1223'),
    ]

    operations = [
        migrations.AlterField(
            model_name='restaurante',
            name='foto',
            field=cloudinary.models.CloudinaryField(max_length=255, null=True, verbose_name='foto'),
        ),
        migrations.AlterField(
            model_name='tipo',
            name='foto',
            field=cloudinary.models.CloudinaryField(max_length=255, null=True, verbose_name='foto'),
        ),
        migrations.AlterField(
            model_name='usuario',
            name='foto',
            field=cloudinary.models.CloudinaryField(max_length=255, null=True, verbose_name='foto'),
        ),
    ]
