# Generated by Django 2.2.4 on 2019-09-17 18:57

import cloudinary.models
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Delivery', '0003_auto_20190916_1306'),
    ]

    operations = [
        migrations.AlterField(
            model_name='fotos_restaurante',
            name='foto',
            field=cloudinary.models.CloudinaryField(max_length=255, null=True, verbose_name='imagem'),
        ),
    ]
