# Generated by Django 2.2.4 on 2019-11-17 20:13

import cloudinary.models
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('Delivery', '0004_restaurante_dias'),
    ]

    operations = [
        migrations.AlterField(
            model_name='codimentos',
            name='preco',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=8),
        ),
        migrations.CreateModel(
            name='Cardapio',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(max_length=100)),
                ('preco', models.DecimalField(decimal_places=2, max_digits=8)),
                ('quantidade', models.CharField(max_length=100)),
                ('foto', cloudinary.models.CloudinaryField(max_length=255, null=True, verbose_name='foto')),
                ('restaurante', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='Delivery.Restaurante')),
            ],
        ),
    ]
