# Generated by Django 2.2.4 on 2019-11-30 15:49

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('Delivery', '0005_auto_20191117_1813'),
    ]

    operations = [
        migrations.AddField(
            model_name='cardapio',
            name='destaque',
            field=models.BooleanField(default=False, null=True),
        ),
        migrations.CreateModel(
            name='Codimentos_Restaurante',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('codimentos', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='Delivery.Codimentos')),
                ('restaurante', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='Delivery.Restaurante')),
            ],
        ),
    ]
