# Generated by Django 2.2.4 on 2019-09-22 00:46

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('Delivery', '0005_auto_20190921_2130'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='restaurante',
            name='classificacao',
        ),
        migrations.RemoveField(
            model_name='usuario',
            name='classificacao',
        ),
        migrations.AddField(
            model_name='classificacao_restaurante',
            name='restaurante',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='Delivery.Restaurante'),
        ),
        migrations.AddField(
            model_name='classificacao_usuario',
            name='usuario',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='Delivery.Usuario'),
        ),
    ]
