# Generated by Django 2.2.4 on 2019-12-25 23:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Delivery', '0007_auto_20191225_2114'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='codimentos',
            name='restaurante',
        ),
        migrations.AddField(
            model_name='codimentos',
            name='preco',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=8),
        ),
    ]
