# Generated by Django 2.2.4 on 2019-09-22 15:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Delivery', '0007_auto_20190922_1141'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='comida',
            name='ingredientes',
        ),
        migrations.AddField(
            model_name='comida',
            name='ingredientes',
            field=models.ManyToManyField(blank=True, null=True, to='Delivery.Ingredientes'),
        ),
    ]
