# Generated by Django 2.2.4 on 2019-09-22 15:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Delivery', '0008_auto_20190922_1200'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='cardapio',
            name='comidas',
        ),
        migrations.AddField(
            model_name='cardapio',
            name='comidas',
            field=models.ManyToManyField(to='Delivery.Comida'),
        ),
        migrations.AlterField(
            model_name='comida',
            name='ingredientes',
            field=models.ManyToManyField(to='Delivery.Ingredientes'),
        ),
    ]
