# Generated by Django 2.2.4 on 2019-12-26 00:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Delivery', '0008_auto_20191225_2125'),
    ]

    operations = [
        migrations.CreateModel(
            name='Cor',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(max_length=500, unique=True)),
            ],
        ),
        migrations.AddField(
            model_name='restaurante',
            name='cor',
            field=models.ForeignKey(blank=True, null=True, on_delete=True, to='Delivery.Cor'),
        ),
    ]
