# Generated by Django 2.2.4 on 2019-12-27 14:46

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('Delivery', '0009_auto_20191225_2242'),
    ]

    operations = [
        migrations.CreateModel(
            name='Comida_Tag',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('cardapio', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Delivery.Cardapio')),
                ('tag', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Delivery.Tags')),
            ],
        ),
    ]
