# Generated by Django 2.2.5 on 2019-09-24 20:06

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('Delivery', '0009_auto_20190922_1202'),
    ]

    operations = [
        migrations.AlterField(
            model_name='pedido',
            name='nome',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Delivery.Comida'),
        ),
    ]
