# Generated by Django 2.2.4 on 2019-09-27 00:04

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('Delivery', '0010_auto_20190924_2006'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='restaurante',
            name='cardapio',
        ),
        migrations.AddField(
            model_name='cardapio',
            name='restaurante',
            field=models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='Delivery.Restaurante'),
        ),
    ]
